-- Migration 001: Initial schema for Odyssey MVP
-- All tables are prefixed with odyssey_ to avoid collisions in the shared
-- Supabase project. See docs/decisions/ADR-003-database.md and
-- docs/domain-model.md for the entity-to-table mapping.

-- ============================================================
-- odyssey_crews
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_crews (
    id         TEXT PRIMARY KEY,
    name       TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_user_profiles
-- UID is the shared identity across Gatekeeper, Family Reward, and Odyssey.
-- Stores explorer data, crew membership, credential hash, and device binding.
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_user_profiles (
    uid             TEXT PRIMARY KEY,
    crew_id         TEXT    NOT NULL REFERENCES odyssey_crews(id),
    explorer_name   TEXT    NOT NULL,
    role            TEXT    NOT NULL DEFAULT 'SEEKER',
    level           INTEGER NOT NULL DEFAULT 1,
    xp              BIGINT  NOT NULL DEFAULT 0,
    password_hash   TEXT,
    device_id       TEXT,
    created_at      TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at      TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_quests
-- One row per quest instance per crew. Template references are code-embedded
-- slugs (see docs/domain-model.md: Quest template is embedded in code for MVP).
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_quests (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crew_id       TEXT    NOT NULL REFERENCES odyssey_crews(id),
    template_slug TEXT    NOT NULL,
    title         TEXT    NOT NULL,
    status        TEXT    NOT NULL DEFAULT 'PENDING',
    started_at    TIMESTAMPTZ,
    completed_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_challenges
-- Individual challenge instances belonging to a QuestInstance.
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_challenges (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quest_id      BIGINT  NOT NULL REFERENCES odyssey_quests(id) ON DELETE CASCADE,
    slug          TEXT    NOT NULL,
    description   TEXT    NOT NULL,
    status        TEXT    NOT NULL DEFAULT 'PENDING',
    completed_by  TEXT    REFERENCES odyssey_user_profiles(uid),
    completed_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_realm_progress
-- Shared realm progress per crew per realm. The family's collective state
-- in a realm. Multiple rows per crew â€” one per realm.
-- Primary key is composite (crew_id, realm) to support multiple realms.
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_realm_progress (
    crew_id          TEXT    NOT NULL,
    realm            TEXT    NOT NULL,
    status           TEXT    NOT NULL DEFAULT 'LOCKED',
    story_branch     TEXT,
    progress         INTEGER NOT NULL DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
    last_unlocked_at TIMESTAMPTZ,
    updated_at       TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (crew_id, realm)
);

-- ============================================================
-- odyssey_creative_items
-- Append-only log of creative-space contributions.
-- In the MVP, only STORY submissions are accepted (see docs/roadmap.md Phase 1).
-- Payload is base64-encoded text for small MVP payloads.
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_creative_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crew_id    TEXT    NOT NULL REFERENCES odyssey_crews(id),
    realm      TEXT    NOT NULL,
    author_uid TEXT    NOT NULL REFERENCES odyssey_user_profiles(uid),
    kind       TEXT    NOT NULL DEFAULT 'STORY',
    payload    TEXT   NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_daily_turns
-- One per user per calendar day. Tracks daily turn completion.
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_daily_turns (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid        TEXT    NOT NULL REFERENCES odyssey_user_profiles(uid),
    date       DATE    NOT NULL,
    quest_slug TEXT    NOT NULL,
    completed  BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_achievements
-- Personal and group milestones. One row per achievement per player (or crew).
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_achievements (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid        TEXT,
    crew_id    TEXT    REFERENCES odyssey_crews(id),
    code       TEXT    NOT NULL,
    kind       TEXT    NOT NULL DEFAULT 'PERSONAL',
    awarded_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_relics
-- Collectible items tied to achievement or story completion.
-- Personal but displayed on a shared crew gallery (see docs/economy.md).
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_relics (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid        TEXT    NOT NULL REFERENCES odyssey_user_profiles(uid),
    code       TEXT    NOT NULL,
    awarded_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_chests
-- Reward containers with known, fixed contents (no randomization).
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_chests (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid        TEXT    NOT NULL REFERENCES odyssey_user_profiles(uid),
    source     TEXT    NOT NULL,
    opened     BOOLEAN NOT NULL DEFAULT FALSE,
    opened_at  TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- Row-Level Security
-- All odyssey_* tables use service-role RLS policy (same convention as
-- Family Reward). Access control is enforced at the application layer.
-- ============================================================

-- odyssey_crews
ALTER TABLE odyssey_crews ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access" ON odyssey_crews;
CREATE POLICY "Allow service_role full access" ON odyssey_crews FOR ALL USING (true);

-- odyssey_user_profiles
ALTER TABLE odyssey_user_profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on user_profiles" ON odyssey_user_profiles;
CREATE POLICY "Allow service_role full access on user_profiles" ON odyssey_user_profiles FOR ALL USING (true);

-- odyssey_quests
ALTER TABLE odyssey_quests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on quests" ON odyssey_quests;
CREATE POLICY "Allow service_role full access on quests" ON odyssey_quests FOR ALL USING (true);

-- odyssey_challenges
ALTER TABLE odyssey_challenges ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on challenges" ON odyssey_challenges;
CREATE POLICY "Allow service_role full access on challenges" ON odyssey_challenges FOR ALL USING (true);

-- odyssey_realm_progress
ALTER TABLE odyssey_realm_progress ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on realm_progress" ON odyssey_realm_progress;
CREATE POLICY "Allow service_role full access on realm_progress" ON odyssey_realm_progress FOR ALL USING (true);

-- odyssey_creative_items
ALTER TABLE odyssey_creative_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on creative_items" ON odyssey_creative_items;
CREATE POLICY "Allow service_role full access on creative_items" ON odyssey_creative_items FOR ALL USING (true);

-- odyssey_daily_turns
ALTER TABLE odyssey_daily_turns ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on daily_turns" ON odyssey_daily_turns;
CREATE POLICY "Allow service_role full access on daily_turns" ON odyssey_daily_turns FOR ALL USING (true);

-- odyssey_achievements
ALTER TABLE odyssey_achievements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on achievements" ON odyssey_achievements;
CREATE POLICY "Allow service_role full access on achievements" ON odyssey_achievements FOR ALL USING (true);

-- odyssey_relics
ALTER TABLE odyssey_relics ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on relics" ON odyssey_relics;
CREATE POLICY "Allow service_role full access on relics" ON odyssey_relics FOR ALL USING (true);

-- odyssey_chests
ALTER TABLE odyssey_chests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on chests" ON odyssey_chests;
CREATE POLICY "Allow service_role full access on chests" ON odyssey_chests FOR ALL USING (true);
-- Migration 002: Indexes for Odyssey MVP
-- All indexes use the odyssey_ prefix and follow the naming convention
-- idx_<table>_<column> as documented in docs/decisions/ADR-003-database.md

-- odyssey_user_profiles
CREATE INDEX IF NOT EXISTS idx_odyssey_user_profiles_crew_id ON odyssey_user_profiles(crew_id);

-- odyssey_quests
CREATE INDEX IF NOT EXISTS idx_odyssey_quests_crew_id ON odyssey_quests(crew_id);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_odyssey_quests_crew_id_slug
    ON odyssey_quests(crew_id, template_slug);

-- odyssey_challenges
CREATE INDEX IF NOT EXISTS idx_odyssey_challenges_quest_id ON odyssey_challenges(quest_id);

-- odyssey_realm_progress
-- crew_id is already the primary key; no additional index needed.

-- odyssey_creative_items
CREATE INDEX IF NOT EXISTS idx_odyssey_creative_items_crew_id ON odyssey_creative_items(crew_id);
CREATE INDEX IF NOT EXISTS idx_odyssey_creative_items_author_uid ON odyssey_creative_items(author_uid);

-- odyssey_daily_turns
CREATE UNIQUE INDEX IF NOT EXISTS uniq_odyssey_daily_turns_uid_date
    ON odyssey_daily_turns(uid, date);

-- odyssey_achievements
CREATE INDEX IF NOT EXISTS idx_odyssey_achievements_uid ON odyssey_achievements(uid);
CREATE INDEX IF NOT EXISTS idx_odyssey_achievements_crew_id ON odyssey_achievements(crew_id);

-- odyssey_relics
CREATE INDEX IF NOT EXISTS idx_odyssey_relics_uid ON odyssey_relics(uid);

-- odyssey_chests
CREATE INDEX IF NOT EXISTS idx_odyssey_chests_uid ON odyssey_chests(uid);
-- Migration 003: Create missing tables for odyssey_system_config and odyssey_creative_submissions
-- These tables are referenced by production code but were never created in the migration sequence.

-- ===========================================================
-- odyssey_system_config â€” shared system configuration storage
-- Mirrors Family Reward's system_configs but under odyssey_ namespace.
-- ===========================================================
CREATE TABLE IF NOT EXISTS odyssey_system_config (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at  TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_odyssey_system_config_key
  ON odyssey_system_config (key);

-- ===========================================================
-- odyssey_creative_submissions â€” append-only log of creative quest submissions
-- In the MVP, only STORY submissions are accepted (see docs/roadmap.md Phase 1).
-- Payload is base64-encoded text for small MVP payloads.
-- ===========================================================
CREATE TABLE IF NOT EXISTS odyssey_creative_submissions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quest_id        BIGINT    NOT NULL,
    challenge_id    BIGINT    NOT NULL,
    crew_id         TEXT      NOT NULL,
    author_uid      TEXT      NOT NULL,
    kind            TEXT      NOT NULL DEFAULT 'STORY',
    content         TEXT      NOT NULL,
    status          TEXT      NOT NULL DEFAULT 'PENDING',
    reviewed_by     TEXT,
    reviewed_at     TIMESTAMPTZ,
    rejection_reason TEXT,
    created_at      TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at      TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    FOREIGN KEY (quest_id) REFERENCES odyssey_quests(id) ON DELETE CASCADE,
    FOREIGN KEY (crew_id) REFERENCES odyssey_crews(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_odyssey_creative_submissions_quest_id
  ON odyssey_creative_submissions (quest_id);

CREATE INDEX IF NOT EXISTS idx_odyssey_creative_submissions_crew_id
  ON odyssey_creative_submissions (crew_id);

CREATE INDEX IF NOT EXISTS idx_odyssey_creative_submissions_author_uid
  ON odyssey_creative_submissions (author_uid);

CREATE INDEX IF NOT EXISTS idx_odyssey_creative_submissions_status
  ON odyssey_creative_submissions (status);

-- Enable RLS
ALTER TABLE odyssey_system_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_creative_submissions ENABLE ROW LEVEL SECURITY;

-- Service role policy (mirrors existing convention)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_system_config'
    AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_system_config FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_creative_submissions'
    AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_creative_submissions FOR ALL TO service_role USING (true)';
  END IF;
END $$;

-- ===========================================================
-- Schema version tracking
-- ===========================================================
CREATE TABLE IF NOT EXISTS odyssey_schema_version (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL,
    updated_at  TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

INSERT INTO odyssey_schema_version (key, value)
VALUES ('schema_version', '3')
ON CONFLICT (key) DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = timezone('utc'::text, now());
-- Chest & Relic System expansion (Milestone: Chest & Relic)
-- No breaking migrations: only ADD COLUMN and CREATE TABLE

-- Expand odyssey_chests with type metadata
ALTER TABLE odyssey_chests
  ADD COLUMN IF NOT EXISTS chest_slug TEXT,
  ADD COLUMN IF NOT EXISTS rarity TEXT,
  ADD COLUMN IF NOT EXISTS icon TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS drop_table TEXT;

-- Expand odyssey_relics with template metadata and owned_count
ALTER TABLE odyssey_relics
  ADD COLUMN IF NOT EXISTS slug TEXT,
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS realm TEXT,
  ADD COLUMN IF NOT EXISTS rarity TEXT,
  ADD COLUMN IF NOT EXISTS image TEXT,
  ADD COLUMN IF NOT EXISTS lore TEXT,
  ADD COLUMN IF NOT EXISTS owned_count INTEGER DEFAULT 1;

-- odyssey_player_relics tracks per-player relic collection state
CREATE TABLE IF NOT EXISTS odyssey_player_relics (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  uid TEXT NOT NULL,
  relic_slug TEXT NOT NULL,
  relic_id BIGINT,
  owned_count INTEGER DEFAULT 1,
  discovered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_odyssey_player_relics_uid_slug
  ON odyssey_player_relics (uid, relic_slug);

CREATE INDEX IF NOT EXISTS idx_odyssey_player_relics_uid
  ON odyssey_player_relics (uid);

-- Enable RLS
ALTER TABLE odyssey_chests ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_relics ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_player_relics ENABLE ROW LEVEL SECURITY;

-- Service role policy (mirrors existing convention)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_chests' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_chests FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_relics' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_relics FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_player_relics' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_player_relics FOR ALL TO service_role USING (true)';
  END IF;
END $$;
-- Chest & Relic definitions expansion (configurable catalogs)
-- No breaking migrations: only CREATE TABLE

-- odyssey_chest_definitions stores chest templates (admin-managed)
CREATE TABLE IF NOT EXISTS odyssey_chest_definitions (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  rarity TEXT NOT NULL,
  icon TEXT NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_odyssey_chest_definitions_slug
  ON odyssey_chest_definitions (slug);

-- odyssey_drop_tables stores rarity weights per chest definition
CREATE TABLE IF NOT EXISTS odyssey_drop_tables (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  chest_slug TEXT NOT NULL REFERENCES odyssey_chest_definitions(slug) ON DELETE CASCADE,
  rarity TEXT NOT NULL,
  relic_id BIGINT,
  weight DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_odyssey_drop_tables_chest_rarity
  ON odyssey_drop_tables (chest_slug, rarity);

-- odyssey_relic_definitions stores relic templates (admin-managed)
CREATE TABLE IF NOT EXISTS odyssey_relic_definitions (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  realm TEXT NOT NULL,
  rarity TEXT NOT NULL,
  image TEXT NOT NULL,
  lore TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_odyssey_relic_definitions_slug
  ON odyssey_relic_definitions (slug);

CREATE INDEX IF NOT EXISTS idx_odyssey_relic_definitions_realm
  ON odyssey_relic_definitions (realm);

-- Enable RLS
ALTER TABLE odyssey_chest_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_drop_tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_relic_definitions ENABLE ROW LEVEL SECURITY;

-- Service role policies
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_chest_definitions' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_chest_definitions FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_drop_tables' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_drop_tables FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_relic_definitions' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_relic_definitions FOR ALL TO service_role USING (true)';
  END IF;
END $$;
-- Migration 006: Content Definitions Tables
-- All tables use the odyssey_ prefix and follow ADR-003 conventions.
-- RLS is enabled with the service_role full-access policy.

-- ============================================================
-- odyssey_realm_definitions
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_realm_definitions (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  order INTEGER NOT NULL DEFAULT 0,
  max_progress INTEGER NOT NULL DEFAULT 100,
  icon TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_odyssey_realm_definitions_slug
  ON odyssey_realm_definitions (slug);

CREATE INDEX IF NOT EXISTS idx_odyssey_realm_definitions_order
  ON odyssey_realm_definitions ("order");

-- ============================================================
-- odyssey_chapter_definitions
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_chapter_definitions (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  realm TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_odyssey_chapter_definitions_slug
  ON odyssey_chapter_definitions (slug);

CREATE INDEX IF NOT EXISTS idx_odyssey_chapter_definitions_realm
  ON odyssey_chapter_definitions (realm);

-- ============================================================
-- odyssey_quest_definitions
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_quest_definitions (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  realm TEXT NOT NULL,
  chapter TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  quest_type TEXT NOT NULL DEFAULT 'SOLO',
  challenge_defs JSONB NOT NULL DEFAULT '[]',
  reward_xp BIGINT NOT NULL DEFAULT 0,
  reward_chest TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_odyssey_quest_definitions_slug
  ON odyssey_quest_definitions (slug);

CREATE INDEX IF NOT EXISTS idx_odyssey_quest_definitions_realm
  ON odyssey_quest_definitions (realm);

-- ============================================================
-- odyssey_creative_prompt_definitions
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_creative_prompt_definitions (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  realm TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  prompt TEXT NOT NULL DEFAULT '',
  kind TEXT NOT NULL DEFAULT 'STORY',
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_odyssey_creative_prompt_definitions_slug
  ON odyssey_creative_prompt_definitions (slug);

CREATE INDEX IF NOT EXISTS idx_odyssey_creative_prompt_definitions_realm
  ON odyssey_creative_prompt_definitions (realm);

-- ============================================================
-- odyssey_achievement_definitions
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_achievement_definitions (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  kind TEXT NOT NULL DEFAULT 'PERSONAL',
  threshold INTEGER NOT NULL DEFAULT 1,
  reward_xp BIGINT NOT NULL DEFAULT 0,
  reward_relic TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_odyssey_achievement_definitions_code
  ON odyssey_achievement_definitions (code);

-- ============================================================
-- odyssey_season_definitions
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_season_definitions (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  start_at TIMESTAMPTZ NOT NULL,
  end_at TIMESTAMPTZ NOT NULL,
  realm TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_odyssey_season_definitions_slug
  ON odyssey_season_definitions (slug);

-- ============================================================
-- odyssey_lore_definitions
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_lore_definitions (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  realm TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL DEFAULT '',
  order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_odyssey_lore_definitions_slug
  ON odyssey_lore_definitions (slug);

CREATE INDEX IF NOT EXISTS idx_odyssey_lore_definitions_realm
  ON odyssey_lore_definitions (realm);

-- ============================================================
-- Row-Level Security
-- All odyssey_* tables use service-role RLS policy.
-- ============================================================

ALTER TABLE odyssey_realm_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_chapter_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_quest_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_creative_prompt_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_achievement_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_season_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_lore_definitions ENABLE ROW LEVEL SECURITY;

-- Service role policies
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_realm_definitions' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_realm_definitions FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_chapter_definitions' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_chapter_definitions FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_quest_definitions' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_quest_definitions FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_creative_prompt_definitions' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_creative_prompt_definitions FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_achievement_definitions' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_achievement_definitions FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_season_definitions' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_season_definitions FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_lore_definitions' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_lore_definitions FOR ALL TO service_role USING (true)';
  END IF;
END $$;
-- Migration 007: World Progression System
-- Adds tables and columns for chapter progression, lore unlocks,
-- seasonal content filtering, quest prerequisites, and achievement triggers.
-- All new columns are additive (nullable with defaults) â€” no breaking changes.
-- Follows ADR-003 conventions: odyssey_ prefix, snake_case, timestamps, RLS,
-- service_role policy.

-- ============================================================
-- ALTER: odyssey_quest_definitions â€” add prerequisite & seasonality columns
-- ============================================================
ALTER TABLE odyssey_quest_definitions
    ADD COLUMN IF NOT EXISTS is_mandatory      BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS required_quest_slug TEXT,
    ADD COLUMN IF NOT EXISTS required_chapter     TEXT,
    ADD COLUMN IF NOT EXISTS required_realm       TEXT,
    ADD COLUMN IF NOT EXISTS required_level       INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS season_slug          TEXT;

CREATE INDEX IF NOT EXISTS idx_odyssey_quest_definitions_season
    ON odyssey_quest_definitions (season_slug);
CREATE INDEX IF NOT EXISTS idx_odyssey_quest_definitions_required_chapter
    ON odyssey_quest_definitions (required_chapter);
CREATE INDEX IF NOT EXISTS idx_odyssey_quest_definitions_chapter
    ON odyssey_quest_definitions (chapter);

-- ============================================================
-- ALTER: odyssey_lore_definitions â€” link lore to chapters & seasons
-- ============================================================
ALTER TABLE odyssey_lore_definitions
    ADD COLUMN IF NOT EXISTS chapter     TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS season_slug TEXT;

CREATE INDEX IF NOT EXISTS idx_odyssey_lore_definitions_chapter
    ON odyssey_lore_definitions (chapter);
CREATE INDEX IF NOT EXISTS idx_odyssey_lore_definitions_season
    ON odyssey_lore_definitions (season_slug);

-- ============================================================
-- ALTER: odyssey_achievement_definitions â€” add trigger & seasonality
-- The `trigger` column defines what event kinds activate this achievement.
-- Values are free-text to stay definition-driven (no hardcoded enums in DB).
-- ============================================================
ALTER TABLE odyssey_achievement_definitions
    ADD COLUMN IF NOT EXISTS trigger     TEXT NOT NULL DEFAULT 'QUEST_COMPLETED',
    ADD COLUMN IF NOT EXISTS season_slug TEXT;

CREATE INDEX IF NOT EXISTS idx_odyssey_achievement_definitions_trigger
    ON odyssey_achievement_definitions (trigger);
CREATE INDEX IF NOT EXISTS idx_odyssey_achievement_definitions_season
    ON odyssey_achievement_definitions (season_slug);

-- ============================================================
-- ALTER: odyssey_creative_prompt_definitions â€” add seasonality
-- ============================================================
ALTER TABLE odyssey_creative_prompt_definitions
    ADD COLUMN IF NOT EXISTS season_slug TEXT;

CREATE INDEX IF NOT EXISTS idx_odyssey_creative_prompt_definitions_season
    ON odyssey_creative_prompt_definitions (season_slug);

-- ============================================================
-- ALTER: odyssey_chest_definitions â€” add seasonality
-- ============================================================
ALTER TABLE odyssey_chest_definitions
    ADD COLUMN IF NOT EXISTS season_slug TEXT;

CREATE INDEX IF NOT EXISTS idx_odyssey_chest_definitions_season
    ON odyssey_chest_definitions (season_slug);

-- ============================================================
-- ALTER: odyssey_achievements (player achievements) â€” add trigger & count
-- ============================================================
ALTER TABLE odyssey_achievements
    ADD COLUMN IF NOT EXISTS trigger       TEXT,
    ADD COLUMN IF NOT EXISTS completion_count INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_odyssey_achievements_trigger
    ON odyssey_achievements (trigger);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_odyssey_achievements_uid_code
    ON odyssey_achievements (uid, code)
    WHERE uid IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uniq_odyssey_achievements_crew_id_code
    ON odyssey_achievements (crew_id, code)
    WHERE crew_id IS NOT NULL AND uid IS NULL;

-- ============================================================
-- CREATE: odyssey_chapter_progress
-- Tracks a crew's progress through each chapter.
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_chapter_progress (
    crew_id      TEXT    NOT NULL,
    chapter      TEXT    NOT NULL,
    realm        TEXT    NOT NULL,
    status       TEXT    NOT NULL DEFAULT 'LOCKED',
    completed_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at   TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (crew_id, chapter)
);

CREATE INDEX IF NOT EXISTS idx_odyssey_chapter_progress_crew_id
    ON odyssey_chapter_progress (crew_id);
CREATE INDEX IF NOT EXISTS idx_odyssey_chapter_progress_realm
    ON odyssey_chapter_progress (realm);
CREATE INDEX IF NOT EXISTS idx_odyssey_chapter_progress_status
    ON odyssey_chapter_progress (status);

-- ============================================================
-- CREATE: odyssey_lore_unlocks
-- Tracks which lore entries a crew has unlocked.
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_lore_unlocks (
    crew_id     TEXT NOT NULL,
    lore_slug   TEXT NOT NULL,
    realm       TEXT NOT NULL,
    chapter     TEXT NOT NULL DEFAULT '',
    unlocked_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (crew_id, lore_slug)
);

CREATE INDEX IF NOT EXISTS idx_odyssey_lore_unlocks_crew_id
    ON odyssey_lore_unlocks (crew_id);
CREATE INDEX IF NOT EXISTS idx_odyssey_lore_unlocks_lore_slug
    ON odyssey_lore_unlocks (lore_slug);

-- ============================================================
-- ALTER: odyssey_quests â€” add chapter column for instance tracking
-- ============================================================
ALTER TABLE odyssey_quests
    ADD COLUMN IF NOT EXISTS chapter TEXT NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_odyssey_quests_chapter
    ON odyssey_quests (chapter);
CREATE INDEX IF NOT EXISTS idx_odyssey_quests_status
    ON odyssey_quests (status);

-- ============================================================
-- Row-Level Security for new tables
-- ============================================================
ALTER TABLE odyssey_chapter_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_lore_unlocks ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public' AND tablename = 'odyssey_chapter_progress'
        AND policyname = 'Allow service_role full access'
    ) THEN
        EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_chapter_progress FOR ALL TO service_role USING (true)';
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public' AND tablename = 'odyssey_lore_unlocks'
        AND policyname = 'Allow service_role full access'
    ) THEN
        EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_lore_unlocks FOR ALL TO service_role USING (true)';
    END IF;
END $$;
-- Migration 008: Live Operations & Production Readiness
-- Adds: content versioning (published/draft/version/updated_by/published_at),
--       soft delete (deleted_at), audit log table, balance config table,
--       indexes, and published_at backfill for existing rows.
-- No breaking changes: all new columns are additive with safe defaults.

-- ============================================================
-- Versioning model:
--   * published BOOLEAN  â€” true = live row visible to players
--   * draft JSONB        â€” working copy snapshot (null = no draft)
--   * version INTEGER    â€” incremented on every draft save / publish
--   * updated_by TEXT    â€” admin UID who last touched the draft
--   * published_at       â€” timestamp of last publish
--   * deleted_at         â€” NULL = active; non-NULL = soft-deleted (hidden from players)
--
-- Workflow:
--   SaveDraft  â†’ set draft JSONB, version++, updated_by = admin
--   Publish    â†’ copy draft JSON to live columns, published=true, published_at=now, version++, clear draft
--   Preview    â†’ read draft JSON (or live columns if no draft)
--   SoftDelete â†’ deleted_at=now(), published=false (hidden from players)
--   Restore    â†’ deleted_at=NULL (and published=true if it was published before)
-- ============================================================

-- ============================================================
-- Versioning + Soft Delete columns for definition tables
-- ============================================================

-- odyssey_realm_definitions
ALTER TABLE odyssey_realm_definitions
    ADD COLUMN IF NOT EXISTS published     BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS draft           JSONB,
    ADD COLUMN IF NOT EXISTS version       INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS updated_by    TEXT,
    ADD COLUMN IF NOT EXISTS published_at  TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS deleted_at    TIMESTAMPTZ;

-- odyssey_chapter_definitions
ALTER TABLE odyssey_chapter_definitions
    ADD COLUMN IF NOT EXISTS published     BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS draft         JSONB,
    ADD COLUMN IF NOT EXISTS version       INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS updated_by    TEXT,
    ADD COLUMN IF NOT EXISTS published_at  TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS deleted_at    TIMESTAMPTZ;

-- odyssey_quest_definitions
ALTER TABLE odyssey_quest_definitions
    ADD COLUMN IF NOT EXISTS published     BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS draft         JSONB,
    ADD COLUMN IF NOT EXISTS version       INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS updated_by    TEXT,
    ADD COLUMN IF NOT EXISTS published_at  TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS deleted_at    TIMESTAMPTZ;

-- odyssey_creative_prompt_definitions
ALTER TABLE odyssey_creative_prompt_definitions
    ADD COLUMN IF NOT EXISTS published     BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS draft         JSONB,
    ADD COLUMN IF NOT EXISTS version       INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS updated_by    TEXT,
    ADD COLUMN IF NOT EXISTS published_at  TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS deleted_at    TIMESTAMPTZ;

-- odyssey_achievement_definitions
ALTER TABLE odyssey_achievement_definitions
    ADD COLUMN IF NOT EXISTS published     BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS draft         JSONB,
    ADD COLUMN IF NOT EXISTS version       INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS updated_by    TEXT,
    ADD COLUMN IF NOT EXISTS published_at  TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS deleted_at    TIMESTAMPTZ;

-- odyssey_season_definitions
ALTER TABLE odyssey_season_definitions
    ADD COLUMN IF NOT EXISTS published     BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS draft         JSONB,
    ADD COLUMN IF NOT EXISTS version       INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS updated_by    TEXT,
    ADD COLUMN IF NOT EXISTS published_at  TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS deleted_at    TIMESTAMPTZ;

-- odyssey_lore_definitions
ALTER TABLE odyssey_lore_definitions
    ADD COLUMN IF NOT EXISTS published     BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS draft         JSONB,
    ADD COLUMN IF NOT EXISTS version       INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS updated_by    TEXT,
    ADD COLUMN IF NOT EXISTS published_at  TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS deleted_at    TIMESTAMPTZ;

-- odyssey_chest_definitions
ALTER TABLE odyssey_chest_definitions
    ADD COLUMN IF NOT EXISTS published     BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS draft         JSONB,
    ADD COLUMN IF NOT EXISTS version       INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS updated_by    TEXT,
    ADD COLUMN IF NOT EXISTS published_at  TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS deleted_at    TIMESTAMPTZ;

-- odyssey_relic_definitions
ALTER TABLE odyssey_relic_definitions
    ADD COLUMN IF NOT EXISTS published     BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS draft         JSONB,
    ADD COLUMN IF NOT EXISTS version       INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS updated_by    TEXT,
    ADD COLUMN IF NOT EXISTS published_at  TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS deleted_at    TIMESTAMPTZ;

-- ============================================================
-- Versioning + Soft Delete for odyssey_drop_tables
-- ============================================================
ALTER TABLE odyssey_drop_tables
    ADD COLUMN IF NOT EXISTS published     BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS draft         JSONB,
    ADD COLUMN IF NOT EXISTS version       INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS updated_by    TEXT,
    ADD COLUMN IF NOT EXISTS published_at  TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS deleted_at    TIMESTAMPTZ;

-- ============================================================
-- Backfill published_at for existing rows (use created_at)
-- Must run after ALTER TABLE adds the published_at column.
-- ============================================================
UPDATE odyssey_realm_definitions      SET published_at = created_at WHERE published_at IS NULL;
UPDATE odyssey_chapter_definitions    SET published_at = created_at WHERE published_at IS NULL;
UPDATE odyssey_quest_definitions      SET published_at = created_at WHERE published_at IS NULL;
UPDATE odyssey_creative_prompt_definitions SET published_at = created_at WHERE published_at IS NULL;
UPDATE odyssey_achievement_definitions SET published_at = created_at WHERE published_at IS NULL;
UPDATE odyssey_season_definitions     SET published_at = created_at WHERE published_at IS NULL;
UPDATE odyssey_lore_definitions       SET published_at = created_at WHERE published_at IS NULL;
UPDATE odyssey_chest_definitions      SET published_at = created_at WHERE published_at IS NULL;
UPDATE odyssey_relic_definitions      SET published_at = created_at WHERE published_at IS NULL;

-- ============================================================
-- Indexes for versioning + soft delete filters
-- ============================================================
-- ContentService queries filter on (published = true, deleted_at IS NULL)
-- Add partial indexes for performance.

CREATE INDEX IF NOT EXISTS idx_odyssey_realm_definitions_published  ON odyssey_realm_definitions (published) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_odyssey_realm_definitions_deleted  ON odyssey_realm_definitions (deleted_at) WHERE deleted_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_odyssey_chapter_definitions_published  ON odyssey_chapter_definitions (published) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_odyssey_chapter_definitions_deleted  ON odyssey_chapter_definitions (deleted_at) WHERE deleted_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_odyssey_quest_definitions_published  ON odyssey_quest_definitions (published) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_odyssey_quest_definitions_deleted  ON odyssey_quest_definitions (deleted_at) WHERE deleted_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_odyssey_creative_prompt_definitions_published  ON odyssey_creative_prompt_definitions (published) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_odyssey_creative_prompt_definitions_deleted  ON odyssey_creative_prompt_definitions (deleted_at) WHERE deleted_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_odyssey_achievement_definitions_published  ON odyssey_achievement_definitions (published) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_odyssey_achievement_definitions_deleted  ON odyssey_achievement_definitions (deleted_at) WHERE deleted_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_odyssey_season_definitions_published  ON odyssey_season_definitions (published) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_odyssey_season_definitions_deleted  ON odyssey_season_definitions (deleted_at) WHERE deleted_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_odyssey_lore_definitions_published  ON odyssey_lore_definitions (published) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_odyssey_lore_definitions_deleted  ON odyssey_lore_definitions (deleted_at) WHERE deleted_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_odyssey_chest_definitions_published  ON odyssey_chest_definitions (published) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_odyssey_chest_definitions_deleted  ON odyssey_chest_definitions (deleted_at) WHERE deleted_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_odyssey_relic_definitions_published  ON odyssey_relic_definitions (published) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_odyssey_relic_definitions_deleted  ON odyssey_relic_definitions (deleted_at) WHERE deleted_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_odyssey_drop_tables_published ON odyssey_drop_tables (published) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_odyssey_drop_tables_deleted ON odyssey_drop_tables (deleted_at) WHERE deleted_at IS NOT NULL;

-- ============================================================
-- odyssey_balance_configs â€” runtime balancing overrides
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_balance_configs (
    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    key        TEXT NOT NULL UNIQUE,
    value      JSONB NOT NULL,
    updated_by TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_odyssey_balance_configs_key ON odyssey_balance_configs (key);

-- RLS + service role policy
ALTER TABLE odyssey_balance_configs ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public' AND tablename = 'odyssey_balance_configs'
        AND policyname = 'Allow service_role full access'
    ) THEN
        EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_balance_configs FOR ALL TO service_role USING (true)';
    END IF;
END $$;

-- ============================================================
-- odyssey_audit_logs â€” admin action audit trail
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_audit_logs (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    resource    TEXT NOT NULL,
    resource_id TEXT,
    operation   TEXT NOT NULL,
    admin_uid   TEXT NOT NULL,
    old_value   JSONB,
    new_value   JSONB,
    created_at  TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_odyssey_audit_logs_resource   ON odyssey_audit_logs (resource);
CREATE INDEX IF NOT EXISTS idx_odyssey_audit_logs_admin_uid  ON odyssey_audit_logs (admin_uid);
CREATE INDEX IF NOT EXISTS idx_odyssey_audit_logs_created_at ON odyssey_audit_logs (created_at);
CREATE INDEX IF NOT EXISTS idx_odyssey_audit_logs_operation  ON odyssey_audit_logs (operation);

-- RLS + service role policy
ALTER TABLE odyssey_audit_logs ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public' AND tablename = 'odyssey_audit_logs'
        AND policyname = 'Allow service_role full access'
    ) THEN
        EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_audit_logs FOR ALL TO service_role USING (true)';
    END IF;
END $$;

-- ============================================================
-- odyssey_system_config â€” existing table; add build_version row
-- (seeded by deployment, not a definition table â€” no versioning needed)
-- ============================================================
-- No schema changes needed; the ConfigStore already reads from odyssey_system_config.
-- Migration 009: Request correlation & observability
-- Adds: request_id column to audit logs, indexes for correlation.
-- Schema version tracking table was created in migration 003.

-- ============================================================
-- Add request_id to audit logs for request correlation
-- ============================================================
ALTER TABLE odyssey_audit_logs ADD COLUMN IF NOT EXISTS request_id TEXT;

CREATE INDEX IF NOT EXISTS idx_odyssey_audit_logs_request_id
    ON odyssey_audit_logs (request_id)
    WHERE request_id IS NOT NULL;

-- ============================================================
-- Schema version tracking
-- ============================================================
INSERT INTO odyssey_schema_version (key, value)
VALUES ('schema_version', '9')
ON CONFLICT (key) DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = timezone('utc'::text, now());

-- RLS + service role policy
ALTER TABLE odyssey_schema_version ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_schema_version'
    AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_schema_version FOR ALL TO service_role USING (true)';
  END IF;
END $$;
-- Migration 010: Seed Playable Content Definitions
-- Seeds every definition table with minimum playable content.
-- All content is published (published=true) and non-deleted.
-- Uses ON CONFLICT DO NOTHING for idempotent execution.
--
-- Prerequisites: migrations 001-009 must be applied first.

-- ============================================================
-- odyssey_realm_definitions
-- ============================================================
INSERT INTO odyssey_realm_definitions (slug, name, description, "order", max_progress, icon, published, version)
VALUES
  ('whispering-woods', 'Whispering Woods', 'A gentle forest realm of moss, light, and quiet secrets.', 1, 100, 'ðŸŒ²', true, 1),
  ('clockwork-city', 'Clockwork City', 'A bustling city of gears, steam, and copper curiosities.', 2, 100, 'âš™ï¸', true, 1),
  ('starlit-library', 'Starlit Library', 'A vast library floating among the stars, filled with ancient knowledge.', 3, 100, 'ðŸ“š', true, 1)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- odyssey_chapter_definitions
-- ============================================================
INSERT INTO odyssey_chapter_definitions (slug, realm, title, description, "order", published, version)
VALUES
  ('the-awakening', 'whispering-woods', 'The Awakening', 'The forest wakes around you. Learn to see what others miss.', 1, true, 1),
  ('the-deep-woods', 'whispering-woods', 'The Deep Woods', 'Venture deeper into the forest where shadows hold stories.', 2, true, 1),
  ('gears-and-gold', 'clockwork-city', 'Gears and Gold', 'Discover the clockwork heart of the city and its hidden treasures.', 1, true, 1),
  ('first-stars', 'starlit-library', 'First Stars', 'The library opens its doors to those who look upward.', 1, true, 1)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- odyssey_quest_definitions
-- ============================================================
INSERT INTO odyssey_quest_definitions (slug, realm, chapter, title, description, quest_type, challenge_defs, reward_xp, reward_chest, is_mandatory, required_level, published, version)
VALUES
  -- Realm 1, Chapter 1: The Awakening
  ('morning-light', 'whispering-woods', 'the-awakening', 'Morning Light', 'Find something glistening outside your door and share what you discovered.', 'SOLO', '[{"slug":"find-the-dew","description":"Find something glistening outside your door and describe it.","type":"OBSERVATION"},{"slug":"morning-fact","description":"Look up one fact about morning sunlight and share it.","type":"RESEARCH"}]', 80, 'wooden-chest', true, 0, true, 1),
  ('gather-herbs', 'whispering-woods', 'the-awakening', 'Gather Herbs', 'Point out three shades of green and name one use for a common houseplant.', 'SOLO', '[{"slug":"spot-the-green","description":"Point out three shades of green you can see right now.","type":"OBSERVATION"},{"slug":"herb-lore","description":"Name one use for a common houseplant.","type":"RESEARCH"}]', 80, 'wooden-chest', true, 0, true, 1),
  ('riddle-of-the-stones', 'whispering-woods', 'the-awakening', 'Riddle of the Stones', 'Find a stone or brick and solve the riddle it poses.', 'SOLO', '[{"slug":"stone-shape","description":"Find a stone or brick and describe its shape.","type":"OBSERVATION"},{"slug":"solve-riddle","description":"Solve: I have no voice, yet I answer every question. What am I?","type":"PUZZLE"}]', 100, 'bronze-chest', true, 0, true, 1),

  -- Realm 1, Chapter 2: The Deep Woods
  ('shadow-trail', 'whispering-woods', 'the-deep-woods', 'Shadow Trail', 'Follow the shadow that appears when the light shifts.', 'SOLO', '[{"slug":"trace-shadow","description":"Trace the shape of a shadow on the ground and describe it.","type":"OBSERVATION"},{"slug":"shadow-story","description":"Invent a short story about where the shadow leads.","type":"WRITE"}]', 100, 'bronze-chest', true, 0, true, 1),
  ('the-old-growth', 'whispering-woods', 'the-deep-woods', 'The Old Growth', 'Draw the oldest tree you can find and write about its history.', 'SOLO', '[{"slug":"draw-tree","description":"Draw or describe the oldest tree you can see.","type":"DRAW"},{"slug":"tree-history","description":"Write a short paragraph about what this tree has witnessed.","type":"WRITE"}]', 120, 'silver-chest', true, 0, true, 1),
  ('forest-riddle', 'whispering-woods', 'the-deep-woods', 'Forest Riddle', 'Solve the forest riddle and find the hidden marker.', 'SOLO', '[{"slug":"riddle-solve","description":"Solve the riddle: I am always hungry, I must always be fed. The finger I touch will soon turn red. What am I?","type":"PUZZLE"},{"slug":"find-marker","description":"Find a natural marker (stone, stick, leaf) that matches the riddle answer.","type":"OBSERVATION"}]', 120, 'silver-chest', true, 0, true, 1),

  -- Realm 2, Chapter 1: Gears and Gold
  ('clockwork-intro', 'clockwork-city', 'gears-and-gold', 'Clockwork Introduction', 'Observe the mechanical world around you and note three gears or springs.', 'SOLO', '[{"slug":"find-gears","description":"Find three mechanical objects with gears or springs.","type":"OBSERVATION"},{"slug":"gear-fact","description":"Research one fact about how clocks or gears work.","type":"RESEARCH"}]', 100, 'bronze-chest', true, 0, true, 1),
  ('gear-hunt', 'clockwork-city', 'gears-and-gold', 'Gear Hunt', 'Search for a copper or brass object and describe its shape.', 'SOLO', '[{"slug":"copper-find","description":"Find a copper or brass object and describe its shape and texture.","type":"OBSERVATION"},{"slug":"gear-puzzle","description":"Solve a simple mechanical puzzle or riddle about gears.","type":"PUZZLE"}]', 120, 'silver-chest', true, 0, true, 1),
  ('the-copper-key', 'clockwork-city', 'gears-and-gold', 'The Copper Key', 'Write a story about finding a key that opens a clockwork door.', 'SOLO', '[{"slug":"key-story","description":"Write a short story about finding a mysterious copper key.","type":"WRITE"},{"slug":"key-research","description":"Research one fact about locks or keys in history.","type":"RESEARCH"}]', 140, 'silver-chest', true, 0, true, 1),

  -- Realm 3, Chapter 1: First Stars
  ('star-observation', 'starlit-library', 'first-stars', 'Star Observation', 'Look at the sky and identify one constellation or bright star.', 'SOLO', '[{"slug":"find-constellation","description":"Find and name one constellation or bright star in the night sky.","type":"OBSERVATION"},{"slug":"star-fact","description":"Research one fact about the star or constellation you found.","type":"RESEARCH"}]', 100, 'bronze-chest', true, 0, true, 1),
  ('constellation-map', 'starlit-library', 'first-stars', 'Constellation Map', 'Draw your own constellation map and write the story behind it.', 'SOLO', '[{"slug":"draw-map","description":"Draw a map of the stars you can see, connecting them into a pattern.","type":"DRAW"},{"slug":"map-story","description":"Write the story of the constellation you invented.","type":"WRITE"}]', 120, 'silver-chest', true, 0, true, 1),
  ('library-lore', 'starlit-library', 'first-stars', 'Library Lore', 'Research a famous library from history and share what you learned.', 'SOLO', '[{"slug":"library-research","description":"Research one famous library from history (Alexandria, etc.).","type":"RESEARCH"},{"slug":"library-reflection","description":"Write a short reflection on why libraries matter.","type":"WRITE"}]', 140, 'golden-chest', true, 0, true, 1)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- odyssey_creative_prompt_definitions
-- ============================================================
INSERT INTO odyssey_creative_prompt_definitions (slug, realm, title, description, prompt, kind, published, version)
VALUES
  ('whisper-story', 'whispering-woods', 'Whisper Story', 'Write a short story about a secret the forest told you.', 'The trees are whispering. What secret do they share with you? Write a short story (50-200 words) about what the forest reveals.', 'STORY', true, 1),
  ('forest-drawing', 'whispering-woods', 'Forest Drawing', 'Draw what you imagine lives between the trees.', 'Close your eyes and imagine what lives between the trees in the Whispering Woods. Draw it.', 'DRAW', true, 1),
  ('clockwork-story', 'clockwork-city', 'Clockwork Story', 'Write a story about a machine that thinks for itself.', 'In Clockwork City, a machine wakes up and starts thinking. What does it think about? Write a short story.', 'STORY', true, 1),
  ('gear-drawing', 'clockwork-city', 'Gear Drawing', 'Draw your ideal clockwork invention.', 'If you could build one clockwork invention, what would it do? Draw it and label the parts.', 'DRAW', true, 1),
  ('starlit-story', 'starlit-library', 'Starlit Story', 'Write about a book that writes itself.', 'In the Starlit Library, books write themselves overnight. What story appears on the page when you open one?', 'STORY', true, 1),
  ('constellation-drawing', 'starlit-library', 'Constellation Drawing', 'Draw a new constellation and give it a name.', 'The stars are waiting for someone to connect them into a new shape. Draw your constellation and name it.', 'DRAW', true, 1)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- odyssey_achievement_definitions
-- ============================================================
INSERT INTO odyssey_achievement_definitions (code, title, description, kind, trigger, threshold, reward_xp, reward_relic, published, version)
VALUES
  ('FIRST_QUEST', 'First Quest', 'Complete your first quest.', 'PERSONAL', 'QUEST_COMPLETED', 1, 50, '', true, 1),
  ('CHAPTER_COMPLETE', 'Chapter Complete', 'Finish all quests in a chapter.', 'GROUP', 'CHAPTER_COMPLETED', 1, 100, '', true, 1),
  ('REALM_COMPLETE', 'Realm Complete', 'Complete all chapters in a realm.', 'GROUP', 'REALM_COMPLETED', 1, 200, '', true, 1),
  ('DAILY_STREAK_3', 'Three-Day Streak', 'Complete daily turns for 3 consecutive days.', 'PERSONAL', 'DAILY_STREAK', 3, 30, '', true, 1),
  ('DAILY_STREAK_7', 'Seven-Day Streak', 'Complete daily turns for 7 consecutive days.', 'PERSONAL', 'DAILY_STREAK', 7, 70, '', true, 1),
  ('FIRST_CHEST', 'First Chest', 'Open your first chest.', 'PERSONAL', 'CHEST_OPENED', 1, 25, '', true, 1),
  ('FIRST_RELIC', 'First Relic', 'Collect your first relic.', 'PERSONAL', 'RELIC_COLLECTED', 1, 25, '', true, 1),
  ('EXPLORER_LEVEL_3', 'Explorer Level 3', 'Reach Explorer Level 3.', 'PERSONAL', 'LEVEL_REACHED', 3, 50, '', true, 1),
  ('CREATIVE_FIRST', 'Creative Spark', 'Submit your first creative work.', 'PERSONAL', 'CREATIVE_SUBMISSION', 1, 30, '', true, 1),
  ('QUEST_MASTER', 'Quest Master', 'Complete 10 quests.', 'PERSONAL', 'QUEST_COMPLETED', 10, 100, '', true, 1)
ON CONFLICT (code) DO NOTHING;

-- ============================================================
-- odyssey_lore_definitions
-- ============================================================
INSERT INTO odyssey_lore_definitions (slug, realm, chapter, title, content, "order", published, version)
VALUES
  ('forest-origin', 'whispering-woods', 'the-awakening', 'The Origin of the Whispering Woods', 'Long ago, the first trees grew from seeds carried on the wind. Each tree holds a memory, and when the wind blows through the leaves, it whispers those memories to anyone who listens.', 1, true, 1),
  ('forest-creatures', 'whispering-woods', 'the-awakening', 'Creatures of the Forest', 'The Whispering Woods is home to gentle creatures: moss-foxes who glow in the dark, song-birds that remember every melody ever sung, and stone-turtles that carry entire ecosystems on their backs.', 2, true, 1),
  ('forest-deep', 'whispering-woods', 'the-deep-woods', 'Into the Deep Woods', 'Beyond the clearing, the forest grows older. The trees here are so tall their tops disappear into the clouds. The shadows here are not dark â€” they are full of stories waiting to be told.', 1, true, 1),
  ('forest-ancient', 'whispering-woods', 'the-deep-woods', 'The Ancient Oak', 'At the heart of the Deep Woods stands an oak tree so old it remembers the world before names. Its roots drink from underground rivers that flow with starlight.', 2, true, 1),
  ('city-origin', 'clockwork-city', 'gears-and-gold', 'The Birth of Clockwork City', 'Clockwork City was built by inventors who believed that every problem could be solved with a gear, a spring, or a clever idea. The first gear they ever made is still turning in the city center.', 1, true, 1),
  ('city-gold', 'clockwork-city', 'gears-and-gold', 'The Gold Beneath the Gears', 'Beneath the cobblestone streets, veins of copper and brass run through the earth. The city glows at dusk because the metal absorbs the last light of the sun and releases it slowly through the night.', 2, true, 1),
  ('library-origin', 'starlit-library', 'first-stars', 'The Founding of the Starlit Library', 'The Starlit Library was built by the first astronomers, who believed that knowledge should be as vast as the sky. Every book in the library contains a star-map that leads to a new discovery.', 1, true, 1),
  ('library-secrets', 'starlit-library', 'first-stars', 'Secrets of the Shelves', 'The highest shelves in the Starlit Library hold books that have not yet been written. They wait for someone curious enough to climb up and read the blank pages â€” which fill themselves when touched.', 2, true, 1)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- odyssey_chest_definitions
-- ============================================================
INSERT INTO odyssey_chest_definitions (slug, name, rarity, icon, description, published, version)
VALUES
  ('wooden-chest', 'Wooden Chest', 'COMMON', 'ðŸ“¦', 'A simple wooden chest, worn by time but still holding surprises.', true, 1),
  ('bronze-chest', 'Bronze Chest', 'UNCOMMON', 'ðŸŸ¤', 'A sturdy bronze chest with ornate fittings and a satisfying click.', true, 1),
  ('silver-chest', 'Silver Chest', 'RARE', 'âšª', 'A polished silver chest that gleams in the dark. Rare and rewarding.', true, 1),
  ('golden-chest', 'Golden Chest', 'EPIC', 'ðŸŸ¡', 'A magnificent golden chest, warm to the touch and heavy with reward.', true, 1),
  ('mystic-chest', 'Mystic Chest', 'LEGENDARY', 'ðŸ”®', 'An otherworldly chest that hums with arcane energy. The rarest find.', true, 1)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- odyssey_drop_tables
-- ============================================================
INSERT INTO odyssey_drop_tables (chest_slug, rarity, weight)
VALUES
  ('wooden-chest', 'COMMON', 0.70),
  ('wooden-chest', 'UNCOMMON', 0.25),
  ('wooden-chest', 'RARE', 0.05),
  ('bronze-chest', 'COMMON', 0.50),
  ('bronze-chest', 'UNCOMMON', 0.35),
  ('bronze-chest', 'RARE', 0.12),
  ('bronze-chest', 'EPIC', 0.03),
  ('silver-chest', 'COMMON', 0.30),
  ('silver-chest', 'UNCOMMON', 0.35),
  ('silver-chest', 'RARE', 0.25),
  ('silver-chest', 'EPIC', 0.08),
  ('silver-chest', 'LEGENDARY', 0.02),
  ('golden-chest', 'COMMON', 0.15),
  ('golden-chest', 'UNCOMMON', 0.25),
  ('golden-chest', 'RARE', 0.30),
  ('golden-chest', 'EPIC', 0.22),
  ('golden-chest', 'LEGENDARY', 0.08),
  ('mystic-chest', 'COMMON', 0.05),
  ('mystic-chest', 'UNCOMMON', 0.15),
  ('mystic-chest', 'RARE', 0.25),
  ('mystic-chest', 'EPIC', 0.30),
  ('mystic-chest', 'LEGENDARY', 0.25)
ON CONFLICT (chest_slug, rarity) DO NOTHING;

-- ============================================================
-- odyssey_relic_definitions
-- ============================================================
INSERT INTO odyssey_relic_definitions (slug, name, description, realm, rarity, image, lore, published, version)
VALUES
  ('acorn-shard', 'Acorn Shard', 'A tiny piece of an acorn that still glows with warmth.', 'whispering-woods', 'COMMON', 'ðŸŒ°', 'Found in the Whispering Woods. A reminder that great things grow from small beginnings.', true, 1),
  ('copper-gear', 'Copper Gear', 'A small copper gear that still turns when held.', 'clockwork-city', 'COMMON', 'âš™ï¸', 'From the workshops of Clockwork City. It turns in your palm like a tiny sun.', true, 1),
  ('star-dust', 'Star Dust', 'A pinch of shimmering dust that fell from the night sky.', 'starlit-library', 'COMMON', 'âœ¨', 'Collected from the library rooftop on a clear night. It sparkles faintly in moonlight.', true, 1),
  ('whispering-leaf', 'Whispering Leaf', 'A leaf that seems to murmur when you hold it close.', 'whispering-woods', 'UNCOMMON', 'ðŸƒ', 'The trees of the Whispering Woods share their secrets through this leaf.', true, 1),
  ('clock-spring', 'Clock Spring', 'A tightly wound spring from an ancient clockwork mechanism.', 'clockwork-city', 'UNCOMMON', 'ðŸ”©', 'Still wound after centuries. It remembers the time it was made.', true, 1),
  ('moon-page', 'Moon Page', 'A page from a book that only appears under moonlight.', 'starlit-library', 'UNCOMMON', 'ðŸŒ™', 'The ink on this page shifts with the phases of the moon.', true, 1),
  ('ancient-oak', 'Ancient Oak', 'A splinter of the oldest tree in the Whispering Woods.', 'whispering-woods', 'RARE', 'ðŸŒ³', 'This splinter has witnessed a thousand seasons. It hums with quiet power.', true, 1),
  ('brass-compass', 'Brass Compass', 'A compass that always points toward the nearest wonder.', 'clockwork-city', 'RARE', 'ðŸ§­', 'Its needle spins until it finds something worth discovering.', true, 1),
  ('celestial-map', 'Celestial Map', 'A hand-drawn map of stars that no astronomer has charted.', 'starlit-library', 'RARE', 'ðŸ—ºï¸', 'The map reveals constellations that exist only in imagination.', true, 1),
  ('realm-totem', 'Realm Totem', 'A carved totem that represents the heart of a realm.', 'whispering-woods', 'EPIC', 'ðŸº', 'Carved from the heartwood of the world-tree. It resonates with the spirit of the forest.', true, 1),
  ('time-gear', 'Time Gear', 'A gear that seems to tick in reverse.', 'clockwork-city', 'EPIC', 'â³', 'When held, it makes the holder feel the passage of time in their fingertips.', true, 1),
  ('star-compass', 'Star Compass', 'A compass that points not north, but toward the nearest star.', 'starlit-library', 'EPIC', 'â­', 'Its needle always points to the brightest star in the sky.', true, 1),
  ('world-tree-seed', 'World Tree Seed', 'A seed from the tree at the center of all realms.', 'whispering-woods', 'LEGENDARY', 'ðŸŒ°', 'Legend says that planting this seed will grow a tree that connects all worlds.', true, 1),
  ('cosmic-clock', 'Cosmic Clock', 'A clock that measures not hours, but stories.', 'clockwork-city', 'LEGENDARY', 'ðŸ•°ï¸', 'Its hands move whenever a new story begins somewhere in the world.', true, 1),
  ('infinity-library', 'Infinity Library', 'A tiny book that contains an infinite number of pages.', 'starlit-library', 'LEGENDARY', 'ðŸ“–', 'Every time you turn a page, a new story appears. No two readers see the same tale.', true, 1)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- odyssey_season_definitions
-- ============================================================
INSERT INTO odyssey_season_definitions (slug, name, description, start_at, end_at, realm, published, version)
VALUES
  ('season-spring-2026', 'Spring 2026', 'The first season of Odyssey. Explore the Whispering Woods and discover the magic of the forest.', '2026-01-01T00:00:00Z', '2026-12-31T23:59:59Z', 'whispering-woods', true, 1)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- odyssey_balance_configs
-- ============================================================
INSERT INTO odyssey_balance_configs (key, value, updated_by)
VALUES
  ('xp_per_level', '100'::jsonb, 'system'),
  ('challenge_xp', '20'::jsonb, 'system'),
  ('completion_bonus_xp', '60'::jsonb, 'system'),
  ('drop_rate_multiplier', '100'::jsonb, 'system'),
  ('daily_turn_xp', '10'::jsonb, 'system'),
  ('realm_progress_per_quest', '25'::jsonb, 'system'),
  ('realm_completion_threshold', '100'::jsonb, 'system'),
  ('achievement_threshold_multiplier', '100'::jsonb, 'system'),
  ('quest_reward_xp_multiplier', '100'::jsonb, 'system')
ON CONFLICT (key) DO UPDATE SET
  value = EXCLUDED.value,
  updated_by = 'system',
  updated_at = timezone('utc'::text, now());

-- ============================================================
-- Row-Level Security for seed data
-- ============================================================
ALTER TABLE odyssey_realm_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_chapter_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_quest_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_creative_prompt_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_achievement_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_lore_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_chest_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_drop_tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_relic_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_season_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_balance_configs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_realm_definitions' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_realm_definitions FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_chapter_definitions' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_chapter_definitions FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_quest_definitions' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_quest_definitions FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_creative_prompt_definitions' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_creative_prompt_definitions FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_achievement_definitions' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_achievement_definitions FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_lore_definitions' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_lore_definitions FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_chest_definitions' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_chest_definitions FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_drop_tables' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_drop_tables FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_relic_definitions' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_relic_definitions FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_season_definitions' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_season_definitions FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_balance_configs' AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_balance_configs FOR ALL TO service_role USING (true)';
  END IF;
END $$;

-- Update schema version
INSERT INTO odyssey_schema_version (key, value)
VALUES ('schema_version', '10')
ON CONFLICT (key) DO UPDATE SET
  value = EXCLUDED.value,
  updated_at = timezone('utc'::text, now());
-- Migration 011: Add required_quest_slugs for multi-prerequisite quest chains
-- Adds a JSONB column to odyssey_quest_definitions to support multiple
-- quest prerequisites. Existing single prerequisite is preserved in
-- required_quest_slug for backward compatibility.
--
-- Prerequisites: migrations 001-010 must be applied first.

ALTER TABLE odyssey_quest_definitions
  ADD COLUMN IF NOT EXISTS required_quest_slugs JSONB NOT NULL DEFAULT '[]'::jsonb;

-- Update schema version
INSERT INTO odyssey_schema_version (key, value)
VALUES ('schema_version', '11')
ON CONFLICT (key) DO UPDATE SET
  value = EXCLUDED.value,
  updated_at = timezone('utc'::text, now());
-- Migration 012: Reliability & idempotency schema changes
-- 1. Drop the overly restrictive unique index on odyssey_daily_turns(uid, date)
--    The application supports MaxTurnsPerDay > 1, so multiple rows per user per day
--    are valid. The unique index prevented legitimate multiple daily turns.
-- 2. Add a version column to odyssey_user_profiles for optimistic concurrency
--    control on XP/level updates to prevent lost-update races.

-- ============================================================
-- odyssey_daily_turns: remove restrictive unique index
-- ============================================================
DROP INDEX IF EXISTS uniq_odyssey_daily_turns_uid_date;

-- ============================================================
-- odyssey_user_profiles: add version column for optimistic locking
-- ============================================================
ALTER TABLE odyssey_user_profiles
    ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;

-- ============================================================
-- Update schema_version to reflect migration 012
-- ============================================================
INSERT INTO odyssey_schema_version (key, value)
VALUES ('schema_version', '12')
ON CONFLICT (key) DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = timezone('utc'::text, now());
