-- Migration 001: Initial schema for Odyssey MVP
-- All tables are prefixed with odyssey_ to avoid collisions in the shared
-- Supabase project. See docs/decisions/ADR-003-database.md and
-- docs/domain-model.md for the entity-to-table mapping.

-- ============================================================
-- odyssey_crews
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_crews (
    id         TEXT PRIMARY KEY,
    name       TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_user_profiles
-- UID is the shared identity across Gatekeeper, Family Reward, and Odyssey.
-- Stores explorer data, crew membership, credential hash, and device binding.
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_user_profiles (
    uid             TEXT PRIMARY KEY,
    crew_id         TEXT    NOT NULL REFERENCES odyssey_crews(id),
    explorer_name   TEXT    NOT NULL,
    role            TEXT    NOT NULL DEFAULT 'SEEKER',
    level           INTEGER NOT NULL DEFAULT 1,
    xp              BIGINT  NOT NULL DEFAULT 0,
    password_hash   TEXT,
    device_id       TEXT,
    created_at      TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at      TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_quests
-- One row per quest instance per crew. Template references are code-embedded
-- slugs (see docs/domain-model.md: Quest template is embedded in code for MVP).
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_quests (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crew_id       TEXT    NOT NULL REFERENCES odyssey_crews(id),
    template_slug TEXT    NOT NULL,
    title         TEXT    NOT NULL,
    status        TEXT    NOT NULL DEFAULT 'PENDING',
    started_at    TIMESTAMPTZ,
    completed_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_challenges
-- Individual challenge instances belonging to a QuestInstance.
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_challenges (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quest_id      BIGINT  NOT NULL REFERENCES odyssey_quests(id) ON DELETE CASCADE,
    slug          TEXT    NOT NULL,
    description   TEXT    NOT NULL,
    status        TEXT    NOT NULL DEFAULT 'PENDING',
    completed_by  TEXT    REFERENCES odyssey_user_profiles(uid),
    completed_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_realm_progress
-- Shared realm progress per crew per realm. The family's collective state
-- in a realm. Multiple rows per crew — one per realm.
-- Primary key is composite (crew_id, realm) to support multiple realms.
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_realm_progress (
    crew_id          TEXT    NOT NULL,
    realm            TEXT    NOT NULL,
    status           TEXT    NOT NULL DEFAULT 'LOCKED',
    story_branch     TEXT,
    progress         INTEGER NOT NULL DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
    last_unlocked_at TIMESTAMPTZ,
    updated_at       TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (crew_id, realm)
);

-- ============================================================
-- odyssey_creative_items
-- Append-only log of creative-space contributions.
-- In the MVP, only STORY submissions are accepted (see docs/roadmap.md Phase 1).
-- Payload is base64-encoded text for small MVP payloads.
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_creative_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crew_id    TEXT    NOT NULL REFERENCES odyssey_crews(id),
    realm      TEXT    NOT NULL,
    author_uid TEXT    NOT NULL REFERENCES odyssey_user_profiles(uid),
    kind       TEXT    NOT NULL DEFAULT 'STORY',
    payload    TEXT   NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_daily_turns
-- One per user per calendar day. Tracks daily turn completion.
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_daily_turns (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid        TEXT    NOT NULL REFERENCES odyssey_user_profiles(uid),
    date       DATE    NOT NULL,
    quest_slug TEXT    NOT NULL,
    completed  BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_achievements
-- Personal and group milestones. One row per achievement per player (or crew).
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_achievements (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid        TEXT,
    crew_id    TEXT    REFERENCES odyssey_crews(id),
    code       TEXT    NOT NULL,
    kind       TEXT    NOT NULL DEFAULT 'PERSONAL',
    awarded_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_relics
-- Collectible items tied to achievement or story completion.
-- Personal but displayed on a shared crew gallery (see docs/economy.md).
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_relics (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid        TEXT    NOT NULL REFERENCES odyssey_user_profiles(uid),
    code       TEXT    NOT NULL,
    awarded_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_chests
-- Reward containers with known, fixed contents (no randomization).
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_chests (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid        TEXT    NOT NULL REFERENCES odyssey_user_profiles(uid),
    source     TEXT    NOT NULL,
    opened     BOOLEAN NOT NULL DEFAULT FALSE,
    opened_at  TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- Row-Level Security
-- All odyssey_* tables use service-role RLS policy (same convention as
-- Family Reward). Access control is enforced at the application layer.
-- ============================================================

-- odyssey_crews
ALTER TABLE odyssey_crews ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access" ON odyssey_crews;
CREATE POLICY "Allow service_role full access" ON odyssey_crews FOR ALL USING (true);

-- odyssey_user_profiles
ALTER TABLE odyssey_user_profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on user_profiles" ON odyssey_user_profiles;
CREATE POLICY "Allow service_role full access on user_profiles" ON odyssey_user_profiles FOR ALL USING (true);

-- odyssey_quests
ALTER TABLE odyssey_quests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on quests" ON odyssey_quests;
CREATE POLICY "Allow service_role full access on quests" ON odyssey_quests FOR ALL USING (true);

-- odyssey_challenges
ALTER TABLE odyssey_challenges ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on challenges" ON odyssey_challenges;
CREATE POLICY "Allow service_role full access on challenges" ON odyssey_challenges FOR ALL USING (true);

-- odyssey_realm_progress
ALTER TABLE odyssey_realm_progress ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on realm_progress" ON odyssey_realm_progress;
CREATE POLICY "Allow service_role full access on realm_progress" ON odyssey_realm_progress FOR ALL USING (true);

-- odyssey_creative_items
ALTER TABLE odyssey_creative_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on creative_items" ON odyssey_creative_items;
CREATE POLICY "Allow service_role full access on creative_items" ON odyssey_creative_items FOR ALL USING (true);

-- odyssey_daily_turns
ALTER TABLE odyssey_daily_turns ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on daily_turns" ON odyssey_daily_turns;
CREATE POLICY "Allow service_role full access on daily_turns" ON odyssey_daily_turns FOR ALL USING (true);

-- odyssey_achievements
ALTER TABLE odyssey_achievements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on achievements" ON odyssey_achievements;
CREATE POLICY "Allow service_role full access on achievements" ON odyssey_achievements FOR ALL USING (true);

-- odyssey_relics
ALTER TABLE odyssey_relics ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on relics" ON odyssey_relics;
CREATE POLICY "Allow service_role full access on relics" ON odyssey_relics FOR ALL USING (true);

-- odyssey_chests
ALTER TABLE odyssey_chests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on chests" ON odyssey_chests;
CREATE POLICY "Allow service_role full access on chests" ON odyssey_chests FOR ALL USING (true);
