-- Migration 003: Create missing tables for odyssey_system_config and odyssey_creative_submissions
-- These tables are referenced by production code but were never created in the migration sequence.

-- ===========================================================
-- odyssey_system_config — shared system configuration storage
-- Mirrors Family Reward's system_configs but under odyssey_ namespace.
-- ===========================================================
CREATE TABLE IF NOT EXISTS odyssey_system_config (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at  TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_odyssey_system_config_key
  ON odyssey_system_config (key);

-- ===========================================================
-- odyssey_creative_submissions — append-only log of creative quest submissions
-- In the MVP, only STORY submissions are accepted (see docs/roadmap.md Phase 1).
-- Payload is base64-encoded text for small MVP payloads.
-- ===========================================================
CREATE TABLE IF NOT EXISTS odyssey_creative_submissions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quest_id        BIGINT    NOT NULL,
    challenge_id    BIGINT    NOT NULL,
    crew_id         TEXT      NOT NULL,
    author_uid      TEXT      NOT NULL,
    kind            TEXT      NOT NULL DEFAULT 'STORY',
    content         TEXT      NOT NULL,
    status          TEXT      NOT NULL DEFAULT 'PENDING',
    reviewed_by     TEXT,
    reviewed_at     TIMESTAMPTZ,
    rejection_reason TEXT,
    created_at      TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at      TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    FOREIGN KEY (quest_id) REFERENCES odyssey_quests(id) ON DELETE CASCADE,
    FOREIGN KEY (crew_id) REFERENCES odyssey_crews(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_odyssey_creative_submissions_quest_id
  ON odyssey_creative_submissions (quest_id);

CREATE INDEX IF NOT EXISTS idx_odyssey_creative_submissions_crew_id
  ON odyssey_creative_submissions (crew_id);

CREATE INDEX IF NOT EXISTS idx_odyssey_creative_submissions_author_uid
  ON odyssey_creative_submissions (author_uid);

CREATE INDEX IF NOT EXISTS idx_odyssey_creative_submissions_status
  ON odyssey_creative_submissions (status);

-- Enable RLS
ALTER TABLE odyssey_system_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE odyssey_creative_submissions ENABLE ROW LEVEL SECURITY;

-- Service role policy (mirrors existing convention)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_system_config'
    AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_system_config FOR ALL TO service_role USING (true)';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'odyssey_creative_submissions'
    AND policyname = 'Allow service_role full access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow service_role full access" ON odyssey_creative_submissions FOR ALL TO service_role USING (true)';
  END IF;
END $$;

-- ===========================================================
-- Schema version tracking
-- ===========================================================
CREATE TABLE IF NOT EXISTS odyssey_schema_version (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL,
    updated_at  TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

INSERT INTO odyssey_schema_version (key, value)
VALUES ('schema_version', '3')
ON CONFLICT (key) DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = timezone('utc'::text, now());
