-- Migration 023: Slice 2.2 — Cosmetic unlocks (first coin spend path)
-- Additive only. Enables one paid cosmetic: gold avatar frame.

-- Equipped frame on profile (default none = free look).
ALTER TABLE odyssey_user_profiles
  ADD COLUMN IF NOT EXISTS avatar_frame TEXT NOT NULL DEFAULT 'none';

-- Ownership of purchased cosmetics (idempotent via unique constraint).
CREATE TABLE IF NOT EXISTS odyssey_cosmetic_unlocks (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid           TEXT NOT NULL REFERENCES odyssey_user_profiles(uid),
    cosmetic_id   TEXT NOT NULL,
    price_paid    BIGINT NOT NULL DEFAULT 0,
    purchased_at  TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (uid, cosmetic_id)
);

CREATE INDEX IF NOT EXISTS idx_odyssey_cosmetic_unlocks_uid
  ON odyssey_cosmetic_unlocks (uid);

ALTER TABLE odyssey_cosmetic_unlocks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on cosmetic_unlocks" ON odyssey_cosmetic_unlocks;
CREATE POLICY "Allow service_role full access on cosmetic_unlocks"
  ON odyssey_cosmetic_unlocks FOR ALL TO service_role USING (true);

INSERT INTO odyssey_schema_version (key, value)
VALUES ('schema_version', '023_cosmetic_unlocks')
ON CONFLICT (key) DO UPDATE SET
  value = EXCLUDED.value,
  updated_at = timezone('utc'::text, now());
