-- Migration 001: Initial schema for Odyssey MVP
-- All tables are prefixed with odyssey_ to avoid collisions in the shared
-- Supabase project. See docs/decisions/ADR-003-database.md and
-- docs/domain-model.md for the entity-to-table mapping.

-- ============================================================
-- odyssey_families
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_families (
    id         TEXT PRIMARY KEY,
    name       TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_user_profiles
-- UID is the shared identity across Gatekeeper, Family Reward, and Odyssey.
-- Stores explorer data, crew membership, credential hash, and device binding.
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_user_profiles (
    uid             TEXT PRIMARY KEY,
    family_id         TEXT    NOT NULL REFERENCES odyssey_families(id),
    explorer_name   TEXT    NOT NULL,
    role            TEXT    NOT NULL DEFAULT 'SEEKER',
    level           INTEGER NOT NULL DEFAULT 1,
    xp              BIGINT  NOT NULL DEFAULT 0,
    password_hash   TEXT,
    device_id       TEXT,
    created_at      TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at      TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_missions
-- One row per quest instance per crew. Template references are code-embedded
-- slugs (see docs/domain-model.md: Mission template is embedded in code for MVP).
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_missions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id       TEXT    NOT NULL REFERENCES odyssey_families(id),
    template_slug TEXT    NOT NULL,
    title         TEXT    NOT NULL,
    status        TEXT    NOT NULL DEFAULT 'PENDING',
    started_at    TIMESTAMPTZ,
    completed_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_exercises
-- Individual challenge instances belonging to a QuestInstance.
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_exercises (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mission_id      BIGINT  NOT NULL REFERENCES odyssey_missions(id) ON DELETE CASCADE,
    slug          TEXT    NOT NULL,
    description   TEXT    NOT NULL,
    status        TEXT    NOT NULL DEFAULT 'PENDING',
    completed_by  TEXT    REFERENCES odyssey_user_profiles(uid),
    completed_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_journey_progress
-- Shared journey progress per crew per journey. The family's collective state
-- in a journey. Multiple rows per crew — one per journey.
-- Primary key is composite (family_id, journey) to support multiple realms.
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_journey_progress (
    family_id          TEXT    NOT NULL,
    journey            TEXT    NOT NULL,
    status           TEXT    NOT NULL DEFAULT 'LOCKED',
    story_branch     TEXT,
    progress         INTEGER NOT NULL DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
    last_unlocked_at TIMESTAMPTZ,
    updated_at       TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (family_id, journey)
);

-- ============================================================
-- odyssey_creative_items
-- Append-only log of creative-space contributions.
-- In the MVP, only STORY submissions are accepted (see docs/roadmap.md Phase 1).
-- Payload is base64-encoded text for small MVP payloads.
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_creative_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id    TEXT    NOT NULL REFERENCES odyssey_families(id),
    journey      TEXT    NOT NULL,
    author_uid TEXT    NOT NULL REFERENCES odyssey_user_profiles(uid),
    kind       TEXT    NOT NULL DEFAULT 'STORY',
    payload    TEXT   NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_daily_missions
-- One per user per calendar day. Tracks daily turn completion.
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_daily_missions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid        TEXT    NOT NULL REFERENCES odyssey_user_profiles(uid),
    date       DATE    NOT NULL,
    mission_slug TEXT    NOT NULL,
    completed  BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_achievements
-- Personal and group milestones. One row per achievement per player (or crew).
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_achievements (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid        TEXT,
    family_id    TEXT    REFERENCES odyssey_families(id),
    code       TEXT    NOT NULL,
    kind       TEXT    NOT NULL DEFAULT 'PERSONAL',
    awarded_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_collections
-- Collectible items tied to achievement or story completion.
-- Personal but displayed on a shared crew gallery (see docs/economy.md).
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_collections (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid        TEXT    NOT NULL REFERENCES odyssey_user_profiles(uid),
    code       TEXT    NOT NULL,
    awarded_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- odyssey_gifts
-- Reward containers with known, fixed contents (no randomization).
-- ============================================================
CREATE TABLE IF NOT EXISTS odyssey_gifts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid        TEXT    NOT NULL REFERENCES odyssey_user_profiles(uid),
    source     TEXT    NOT NULL,
    opened     BOOLEAN NOT NULL DEFAULT FALSE,
    opened_at  TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- Row-Level Security
-- All odyssey_* tables use service-role RLS policy (same convention as
-- Family Reward). Access control is enforced at the application layer.
-- ============================================================

-- odyssey_families
ALTER TABLE odyssey_families ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access" ON odyssey_families;
CREATE POLICY "Allow service_role full access" ON odyssey_families FOR ALL USING (true);

-- odyssey_user_profiles
ALTER TABLE odyssey_user_profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on user_profiles" ON odyssey_user_profiles;
CREATE POLICY "Allow service_role full access on user_profiles" ON odyssey_user_profiles FOR ALL USING (true);

-- odyssey_missions
ALTER TABLE odyssey_missions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on missions" ON odyssey_missions;
CREATE POLICY "Allow service_role full access on missions" ON odyssey_missions FOR ALL USING (true);

-- odyssey_exercises
ALTER TABLE odyssey_exercises ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on exercises" ON odyssey_exercises;
CREATE POLICY "Allow service_role full access on exercises" ON odyssey_exercises FOR ALL USING (true);

-- odyssey_journey_progress
ALTER TABLE odyssey_journey_progress ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on journey_progress" ON odyssey_journey_progress;
CREATE POLICY "Allow service_role full access on journey_progress" ON odyssey_journey_progress FOR ALL USING (true);

-- odyssey_creative_items
ALTER TABLE odyssey_creative_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on creative_items" ON odyssey_creative_items;
CREATE POLICY "Allow service_role full access on creative_items" ON odyssey_creative_items FOR ALL USING (true);

-- odyssey_daily_missions
ALTER TABLE odyssey_daily_missions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on daily_missions" ON odyssey_daily_missions;
CREATE POLICY "Allow service_role full access on daily_missions" ON odyssey_daily_missions FOR ALL USING (true);

-- odyssey_achievements
ALTER TABLE odyssey_achievements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on achievements" ON odyssey_achievements;
CREATE POLICY "Allow service_role full access on achievements" ON odyssey_achievements FOR ALL USING (true);

-- odyssey_collections
ALTER TABLE odyssey_collections ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on collections" ON odyssey_collections;
CREATE POLICY "Allow service_role full access on collections" ON odyssey_collections FOR ALL USING (true);

-- odyssey_gifts
ALTER TABLE odyssey_gifts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on gifts" ON odyssey_gifts;
CREATE POLICY "Allow service_role full access on gifts" ON odyssey_gifts FOR ALL USING (true);
