-- Migration 020: Phase 2A Social & Identity (Avatars & Reactions)
-- Adds avatar configurations to user profiles and introduces the idempotent reactions table.

-- 1. Avatars
ALTER TABLE odyssey_user_profiles 
ADD COLUMN IF NOT EXISTS avatar_style TEXT NOT NULL DEFAULT 'adventurer',
ADD COLUMN IF NOT EXISTS avatar_seed TEXT NOT NULL DEFAULT 'default-seed';

-- 2. Reactions
-- Idempotent by design: 1 user can only have 1 reaction per target per crew.
-- Enforced via unique constraint.

-- Rename the old prototype table to prevent conflicts
ALTER TABLE IF EXISTS odyssey_reactions RENAME TO odyssey_reactions_legacy;

CREATE TABLE IF NOT EXISTS odyssey_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id TEXT NOT NULL REFERENCES odyssey_families(id),
    target_type TEXT NOT NULL CHECK (target_type IN ('JOURNAL', 'QUEST')),
    target_id BIGINT NOT NULL,
    actor_uid TEXT NOT NULL REFERENCES odyssey_user_profiles(uid),
    reaction_type TEXT NOT NULL CHECK (reaction_type IN ('HEART', 'CLAP', 'STAR')),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Idempotency constraint: 1 user, 1 target, 1 reaction
    UNIQUE (family_id, target_type, target_id, actor_uid)
);

-- Optimize for timeline rendering (fetch all reactions for a set of targets)
CREATE INDEX IF NOT EXISTS idx_odyssey_reactions_target ON odyssey_reactions (family_id, target_type, target_id);

-- Enforce service_role-only access (Application layer Go API handles auth)
ALTER TABLE odyssey_reactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on reactions" ON odyssey_reactions;
CREATE POLICY "Allow service_role full access on reactions" ON odyssey_reactions FOR ALL TO service_role USING (true);

-- Update schema version
INSERT INTO odyssey_schema_version (key, value)
VALUES ('schema_version', '020_social_identity')
ON CONFLICT (key) DO UPDATE SET
  value = EXCLUDED.value,
  updated_at = timezone('utc'::text, now());
