-- Migration 025: Push Subscriptions for PWA Web Push
-- Stores Web Push API subscriptions per explorer (uid).

CREATE TABLE IF NOT EXISTS odyssey_push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid TEXT NOT NULL REFERENCES odyssey_user_profiles(uid),
    endpoint TEXT NOT NULL,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT odyssey_push_subscriptions_uid_endpoint_key UNIQUE (uid, endpoint)
);

CREATE INDEX IF NOT EXISTS idx_odyssey_push_subscriptions_uid
    ON odyssey_push_subscriptions (uid);

ALTER TABLE odyssey_push_subscriptions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow service_role full access on push_subscriptions" ON odyssey_push_subscriptions;
CREATE POLICY "Allow service_role full access on push_subscriptions" ON odyssey_push_subscriptions FOR ALL TO service_role USING (true);

INSERT INTO odyssey_schema_version (key, value)
VALUES ('schema_version', '025_push_subscriptions')
ON CONFLICT (key) DO UPDATE SET
  value = EXCLUDED.value,
  updated_at = timezone('utc'::text, now());
