-- 035_expand_daily_activities.sql
-- Expands daily activities pool from 14 to 45 (adding 31 new activities).

INSERT INTO odyssey_daily_activities (slug, title, question, type, options, correct_answer, explanation, xp_reward, active) VALUES

-- Kesehatan & Kebersihan (6)
('health-1', 'Kesehatan: Cuci Tangan', 'Kapan waktu yang paling kritis untuk mencuci tangan dengan sabun?', 'MCQ', '["Sebelum tidur", "Setelah dari toilet dan sebelum makan", "Saat tangan terlihat kotor saja", "Setelah mandi"]', 'Setelah dari toilet dan sebelum makan', 'Tangan adalah perantara utama penyebaran kuman. Mencuci tangan di saat kritis sangat efektif mencegah penyakit perut.', 10, true),
('health-2', 'Kesehatan: Dehidrasi', 'Apa tanda paling sederhana bahwa tubuh kita kekurangan cairan (dehidrasi)?', 'MCQ', '["Warna urine menjadi kuning gelap pucat", "Tubuh berkeringat", "Mata berair", "Warna urine menjadi kuning pekat atau gelap"]', 'Warna urine menjadi kuning pekat atau gelap', 'Warna urine adalah indikator hidrasi termudah. Kuning terang berarti cukup air, sedangkan gelap berarti dehidrasi.', 10, true),
('health-3', 'Kesehatan: Penggunaan Antibiotik', 'Bolehkah kita mengonsumsi antibiotik sisa jika merasa gejala sakit yang sama berulang?', 'TRUE_FALSE', '["Boleh", "Tidak Boleh"]', 'Tidak Boleh', 'Antibiotik harus diminum sampai habis sesuai resep dokter, dan tidak boleh sembarangan dikonsumsi tanpa resep baru karena bisa memicu kebal kuman.', 10, true),
('health-4', 'Kesehatan: Pertolongan Pertama Luka Bakar', 'Apa langkah pertama yang tepat saat tersiram air panas?', 'MCQ', '["Oleskan pasta gigi", "Siram dengan air mengalir selama 10-15 menit", "Beri kecap atau mentega", "Tutup luka dengan kapas"]', 'Siram dengan air mengalir selama 10-15 menit', 'Air mengalir menurunkan suhu jaringan kulit dan mencegah kerusakan lebih dalam. Pasta gigi atau kecap justru bisa memicu infeksi.', 10, true),
('health-5', 'Kesehatan: Jam Tidur', 'Berapa rata-rata jam tidur yang ideal untuk orang dewasa demi menjaga daya tahan tubuh?', 'MCQ', '["4-5 jam", "7-8 jam", "9-10 jam", "2-3 jam"]', '7-8 jam', 'Tidur 7-8 jam membantu pemulihan sel tubuh, menjaga kesehatan mental, dan memperkuat sistem imun.', 10, true),
('health-6', 'Kesehatan: Menyimpan Makanan', 'Apakah aman menyimpan makanan sisa di suhu ruang (meja makan) selama lebih dari 4 jam?', 'TRUE_FALSE', '["Aman", "Tidak Aman"]', 'Tidak Aman', 'Bakteri pembusuk dan penyebab penyakit berkembang biak sangat cepat di suhu ruang. Makanan sebaiknya segera masuk kulkas maksimal setelah 2 jam.', 10, true),

-- Critical Thinking / Logika (6)
('logic-1', 'Logika: Diskon Palsu', 'Sebuah baju seharga Rp 100.000 dinaikkan menjadi Rp 200.000, lalu didiskon 50%. Apakah pembeli untung?', 'TRUE_FALSE', '["Untung", "Tidak Untung"]', 'Tidak Untung', 'Ini adalah trik mark-up. Harga akhir tetap Rp 100.000. Selalu bandingkan harga akhir dengan harga pasar normal.', 10, true),
('logic-2', 'Logika: Membaca Berita', 'Kamu membaca judul berita sensasional di media sosial yang memicu emosi marah. Apa yang harus dilakukan?', 'MCQ', '["Langsung bagikan ke grup keluarga", "Tulis komentar marah", "Buka link beritanya dan baca isinya utuh", "Report akunnya"]', 'Buka link beritanya dan baca isinya utuh', 'Judul berita sering kali sengaja dibuat memancing emosi (clickbait). Jangan pernah mengambil kesimpulan tanpa membaca keseluruhan artikel.', 10, true),
('logic-3', 'Logika: Korelasi vs Sebab-Akibat', 'Orang yang sering makan es krim juga sering terbakar sinar matahari. Apakah es krim menyebabkan kulit terbakar?', 'TRUE_FALSE', '["Ya", "Tidak"]', 'Tidak', 'Keduanya terjadi di musim panas, namun tidak ada hubungan sebab-akibat langsung. Korelasi belum tentu berarti sebab-akibat.', 10, true),
('logic-4', 'Logika: Skema Cepat Kaya', 'Temanmu menawarkan bisnis jualan suplemen. Kamu mendapat uang jika merekrut anggota baru, bukan dari berjualan produk. Skema apa ini?', 'MCQ', '["Franchise", "Investasi Saham", "Skema Piramida (Penipuan)", "Crowdfunding"]', 'Skema Piramida (Penipuan)', 'Bisnis yang mengandalkan uang masuk dari rekrutmen member baru tanpa penjualan produk riil adalah skema piramida yang ilegal.', 10, true),
('logic-5', 'Logika: Cek Fakta Foto', 'Bagaimana cara sederhana mengecek apakah sebuah foto di internet itu asli atau sekadar editan hoaks lama?', 'MCQ', '["Lihat jumlah like dan share", "Tanya orang di kolom komentar", "Gunakan Google Reverse Image Search", "Percaya saja kalau diposting teman"]', 'Gunakan Google Reverse Image Search', 'Reverse Image Search memungkinkan kita mencari asal-usul foto dan melihat apakah foto itu sudah pernah dipakai untuk berita bohong sebelumnya.', 10, true),
('logic-6', 'Logika: Bukti Anekdotal', '"Kakek saya merokok setiap hari dan usianya 90 tahun, jadi merokok tidak berbahaya." Mengapa argumen ini salah?', 'MCQ', '["Karena merokok mahal", "Karena satu kasus pengecualian tidak membantah data ribuan penelitian medis", "Karena kakek itu pasti berbohong", "Karena rokok zaman dulu beda"]', 'Karena satu kasus pengecualian tidak membantah data ribuan penelitian medis', 'Pengalaman satu orang tidak bisa dijadikan kesimpulan umum untuk mengalahkan data ilmiah yang melibatkan populasi besar.', 10, true),

-- Life Skills (5)
('life-1', 'Life Skill: Membaca Label', 'Di label informasi nilai gizi, bahan komposisi diurutkan berdasarkan apa?', 'MCQ', '["Sesuai abjad", "Dari bahan yang jumlahnya paling banyak ke paling sedikit", "Berdasarkan harga bahan", "Dari bahan yang paling sehat"]', 'Dari bahan yang jumlahnya paling banyak ke paling sedikit', 'Bahan dengan kandungan terbesar selalu diletakkan di urutan pertama pada komposisi produk makanan.', 10, true),
('life-2', 'Life Skill: Api Minyak', 'Jika wajan berisi minyak tiba-tiba terbakar, apa yang TIDAK BOLEH dilakukan?', 'MCQ', '["Menutup dengan tutup panci", "Menutup dengan kain basah", "Menyiram dengan air", "Mematikan kompor"]', 'Menyiram dengan air', 'Air dan minyak panas akan langsung bereaksi meledak dan membuat api membesar seketika (oil fire explosion).', 10, true),
('life-3', 'Life Skill: Kebocoran Gas', 'Apa langkah paling aman jika mencium bau gas LPG yang bocor di dapur?', 'MCQ', '["Nyalakan kipas angin listrik", "Buka jendela lalu cabut selang regulator gas", "Nyalakan lampu dapur agar terang", "Semprot pewangi ruangan"]', 'Buka jendela lalu cabut selang regulator gas', 'Jangan menyalakan/mematikan alat elektronik atau saklar apapun (termasuk lampu/kipas), karena percikan api kecil bisa memicu ledakan.', 10, true),
('life-4', 'Life Skill: Ban Kempes', 'Jika ban kendaraanmu tiba-tiba kempes di tengah jalan raya padat, apa yang harus dilakukan?', 'MCQ', '["Berhenti mendadak di tengah jalan", "Nyalakan lampu hazard dan pinggirkan kendaraan ke bahu jalan perlahan", "Tinggalkan kendaraan di situ", "Paksakan melaju kencang ke bengkel"]', 'Nyalakan lampu hazard dan pinggirkan kendaraan ke bahu jalan perlahan', 'Keamanan diri dan pengguna jalan lain adalah prioritas. Memaksakan melaju bisa merusak velg, dan berhenti di tengah membahayakan.', 10, true),
('life-5', 'Life Skill: Kedaluwarsa', 'Apa perbedaan mendasar antara label "Best Before" dan "Expired Date"?', 'MCQ', '["Sama saja, keduanya tanda makanan basi", "Best before tentang kualitas, Expired date batas aman dikonsumsi", "Best before untuk obat, Expired date untuk makanan", "Expired date bisa diabaikan"]', 'Best before tentang kualitas, Expired date batas aman dikonsumsi', 'Best before menunjukkan kualitas rasa/tekstur menurun, tapi belum tentu bahaya. Expired date adalah batas aman konsumsi untuk kesehatan.', 10, true),

-- Digital Safety Tambahan (3)
('safety-4', 'Digital Safety: Boarding Pass', 'Amankah mengunggah foto utuh tiket pesawat (boarding pass) ke media sosial?', 'TRUE_FALSE', '["Aman", "Tidak Aman"]', 'Tidak Aman', 'Barcode pada boarding pass memuat data pribadi lengkap (nama, nomor identitas, reservasi penerbangan) yang bisa disalahgunakan.', 10, true),
('safety-5', 'Digital Safety: Aplikasi Bajakan', 'Apa risiko terbesar dari mengunduh aplikasi berbayar yang sudah dimodifikasi gratis (APK mod/bajakan)?', 'MCQ', '["Hp jadi lambat", "Bisa menghemat uang", "Bisa disisipi malware penyadap dan pencuri data", "Aplikasi sering crash"]', 'Bisa disisipi malware penyadap dan pencuri data', 'Aplikasi bajakan sering dimanfaatkan peretas untuk menyisipkan program jahat (malware) yang bisa menguasai akun m-banking atau data ponselmu.', 10, true),
('safety-6', 'Digital Safety: 2FA', 'Apa itu 2-Factor Authentication (2FA)?', 'MCQ', '["Password yang panjang", "Membayar untuk keamanan ekstra", "Langkah keamanan tambahan selain password", "Mengunci HP dengan pola"]', 'Langkah keamanan tambahan selain password', '2FA memastikan bahwa meskipun seseorang tahu passwordmu, ia tetap butuh perangkatmu (via SMS/aplikasi Authenticator) untuk bisa masuk.', 10, true),

-- Keuangan Tambahan (4)
('finance-4', 'Finance: Pinjol Ilegal', 'Ciri utama Pinjol Ilegal yang wajib dihindari adalah...', 'MCQ', '["Bunga rendah transparan", "Meminta izin akses seluruh kontak HP dan galeri fotomu", "Proses butuh 2 hari", "Syarat dokumen lengkap"]', 'Meminta izin akses seluruh kontak HP dan galeri fotomu', 'Pinjol ilegal akan menyedot daftar kontak dan fotomu untuk dijadikan alat ancaman/teror jika kamu telat membayar.', 10, true),
('finance-5', 'Finance: Biaya Admin', 'Transfer uang Rp 50.000 beda bank dengan biaya admin Rp 6.500. Berapa persen biaya potongan itu dari nilai transaksi?', 'MCQ', '["1%", "6.5%", "13%", "10%"]', '13%', '(6.500 / 50.000) x 100% = 13%. Jika sering dilakukan, potongan admin untuk transaksi kecil akan sangat merugikan.', 10, true),
('finance-6', 'Finance: Pay Later', 'Fitur "Buy Now Pay Later" pada dasarnya adalah...', 'MCQ', '["Uang gratis", "Diskon belanja", "Bentuk pinjaman uang (utang) dengan bunga", "Dompet elektronik biasa"]', 'Bentuk pinjaman uang (utang) dengan bunga', 'Pay Later adalah bentuk kredit. Telat membayar akan merusak skor kreditmu (SLIK OJK) sehingga menyulitkan cicilan rumah/usaha kelak.', 10, true),
('finance-7', 'Finance: Bunga Berbunga', 'Uang Rp 1 juta diinvestasikan dengan bunga majemuk 10% per tahun. Di akhir tahun ke-2, uangnya menjadi...', 'MCQ', '["Rp 1.100.000", "Rp 1.200.000", "Rp 1.210.000", "Rp 1.500.000"]', 'Rp 1.210.000', 'Tahun 1: 1jt + 100k = 1,1jt. Tahun 2: Bunga 10% dari 1,1jt adalah 110k, sehingga total = 1.210.000.', 10, true),

-- Komunikasi Tambahan (4)
('comm-3', 'Communication: BLUF', 'Saat mengirim email atau pesan tugas penting kepada atasan, apa yang harus diutamakan?', 'MCQ', '["Inti pesan di bagian paling bawah", "Menggunakan bahasa gaul", "Basa-basi panjang", "BLUF (Bottom Line Up Front) / Inti pesan di awal"]', 'BLUF (Bottom Line Up Front) / Inti pesan di awal', 'Di dunia kerja, orang memiliki waktu terbatas. Langsung sampaikan maksud utamamu di awal, lalu berikan detail dan konteksnya.', 10, true),
('comm-4', 'Communication: Kesalahan', 'Kamu membuat kesalahan dalam pekerjaan tim. Respons mana yang paling profesional?', 'MCQ', '["Menyalahkan orang lain", "Diam saja sampai ketahuan", "Maaf, ini kelalaian saya. Ini rencana saya untuk memperbaikinya.", "Maaf, saya lagi banyak pikiran"]', 'Maaf, ini kelalaian saya. Ini rencana saya untuk memperbaikinya.', 'Profesionalisme dinilai dari tanggung jawab dan orientasi pada solusi, bukan dari ketiadaan kesalahan.', 10, true),
('comm-5', 'Communication: Mendengar', 'Apa ciri-ciri mendengarkan aktif (active listening) saat berdiskusi?', 'MCQ', '["Menyiapkan jawaban selagi orang lain bicara", "Melihat ke arah HP", "Menyela agar cepat selesai", "Mengangguk dan mengulang poin penting lawan bicara"]', 'Mengangguk dan mengulang poin penting lawan bicara', 'Mendengarkan aktif bertujuan memastikan pemahaman bersama, bukan sekadar menunggu giliran untuk berbicara.', 10, true),
('comm-6', 'Communication: Nego Gaji', 'Saat negosiasi gaji dengan HRD, mana argumen yang paling rasional dan profesional?', 'MCQ', '["Minta gaji paling tinggi tanpa dasar", "Gunakan data riset standar gaji pasar untuk posisi itu", "Memelas karena banyak utang", "Menerima berapapun yang ditawarkan"]', 'Gunakan data riset standar gaji pasar untuk posisi itu', 'Negosiasi harus berdasarkan data dan value (keahlian) yang kamu bawa ke perusahaan, bukan emosi atau keadaan pribadi.', 10, true),

-- Dunia Kerja Tambahan (3)
('career-4', 'Career: Etika Resign', 'Berapa lama idealnya pemberitahuan pengunduran diri (one month notice) disampaikan ke atasan?', 'MCQ', '["Hari ini resign, besok langsung berhenti", "Minimal 30 hari sebelum hari kerja terakhir", "1 minggu sebelum", "Setelah gajian langsung hilang"]', 'Minimal 30 hari sebelum hari kerja terakhir', 'Notice 30 hari adalah etika profesional agar perusahaan punya waktu mencari pengganti dan kamu bisa menyelesaikan transisi tugas dengan baik.', 10, true),
('career-5', 'Career: Jejak Digital', 'Mungkinkah HRD mengecek akun media sosial pribadi pelamar sebelum menerima lamaran?', 'TRUE_FALSE', '["Mungkin", "Tidak Mungkin"]', 'Mungkin', 'Banyak perusahaan memverifikasi latar belakang kandidat melalui rekam jejak digitalnya. Unggahan provokatif bisa mengancam kariermu.', 10, true),
('career-6', 'Career: NDA', 'Apa fungsi dokumen NDA (Non-Disclosure Agreement) di tempat kerja?', 'MCQ', '["Perjanjian jam kerja", "Kontrak cuti bulanan", "Surat kesepakatan untuk menjaga kerahasiaan data perusahaan", "Daftar inventaris kantor"]', 'Surat kesepakatan untuk menjaga kerahasiaan data perusahaan', 'Membocorkan rahasia perusahaan (seperti data klien, strategi) yang dilindungi NDA dapat berakibat pemecatan bahkan tuntutan hukum.', 10, true)

ON CONFLICT (slug) DO NOTHING;

-- Schema version update
INSERT INTO odyssey_schema_version (key, value)
VALUES ('schema_version', '035_expand_daily_activities')
ON CONFLICT (key) DO UPDATE SET
  value      = EXCLUDED.value,
  updated_at = timezone('utc'::text, now());
